// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5svVvzhx7FlKfND6vKvYga66uJsHvHGg',
    appId: '1:1086791175683:web:c21e56ee2b9e383fc28836',
    messagingSenderId: '1086791175683',
    projectId: 'book-bridge-d3392',
    authDomain: 'book-bridge-d3392.firebaseapp.com',
    storageBucket: 'book-bridge-d3392.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMxTtSOaIoHPxFiPPlTPVZHQS662ZS2kw',
    appId: '1:1086791175683:android:9290821799e61d27c28836',
    messagingSenderId: '1086791175683',
    projectId: 'book-bridge-d3392',
    storageBucket: 'book-bridge-d3392.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1omk2V6Vvy_-4HfXuIqbZGhy7ZeDtcSM',
    appId: '1:1086791175683:ios:ca234d45806084d1c28836',
    messagingSenderId: '1086791175683',
    projectId: 'book-bridge-d3392',
    storageBucket: 'book-bridge-d3392.appspot.com',
    iosClientId: '1086791175683-ftemimhjc7ms4g9nfndap5f44and1d1b.apps.googleusercontent.com',
    iosBundleId: 'com.inti.bookbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1omk2V6Vvy_-4HfXuIqbZGhy7ZeDtcSM',
    appId: '1:1086791175683:ios:ca234d45806084d1c28836',
    messagingSenderId: '1086791175683',
    projectId: 'book-bridge-d3392',
    storageBucket: 'book-bridge-d3392.appspot.com',
    iosClientId: '1086791175683-ftemimhjc7ms4g9nfndap5f44and1d1b.apps.googleusercontent.com',
    iosBundleId: 'com.inti.bookbridge',
  );
}